### ISSUE TITLE
transport: partial/interrupted Read()'s cause incorrect packet length decoding

### ISSUE THREAD

**Issue by weixiaolan2019** [strongswan/govici#34] opened 2020-09-21 01:17 UTC
I have another issue, I don't know how does this happen, this is the code:

```
func (t *transport) recv() (*packet, error) {
buf := make([]byte, headerLength)
t.conn.SetReadDeadline(time.Now().Add(time.Second * 20))
_, err := t.conn.Read(buf)
if err != nil {
if ne, ok := err.(net.Error); ok && ne.Timeout() {
return nil, ne
}
return nil, fmt.Errorf("%v: %v", errTransport, err)
}

================================================================
pl := binary.BigEndian.Uint32(buf)
//netbank.cn
need check the validity of buf length, because sometime the length may be a very very big number, I don't know why
if pl > 1024*10 {
fmt.Fprintf(os.Stderr, "vici recv len %v\n, %s", pl, debug.Stack())
return nil, fmt.Errorf("vici error: recv wrong data len %v", pl)
}
//netbank.cn
================================================================

buf = make([]byte, int(pl))
_, err = t.conn.Read(buf)
if err != nil {
	return nil, fmt.Errorf("%v: %v", errTransport, err)
}

p := &packet{}
err = p.parse(buf)
if err != nil {
	return nil, err
}

return p, nil
}
```

Best,

**Comment by enr0n** [comment] 2020-09-21 13:17
I don't understand the issue you are having.

What happens when a packet is received that is larger than 1024*10?

Also, what are your strongswan and vici package versions?

**Comment by weixiaolan2019** [comment] 2020-09-22 11:10
My strongswan version is 5.8.2, the vici version is v0.2.2 
Infact I don't know what happens when I receive such a large packet, I just load the config to charon. This is the funtion stack.

goroutine 44 [running]:
runtime/debug.Stack(0x2bbe1f0, 0x2a10670, 0x4)
 /home/autobuild/go1.14.3/go/src/runtime/debug/stack.go:24 +0x78
owrt/vendor/github.com/govici/vici.(*transport).recv(0x2bbe1f8, 0x28c1c80, 0x0, 0x0)
 /home/autobuild/project/cpe/linksdwan/workspace/src/owrt/vendor/github.com/govici/vici/transport.go:97 +0x268
owrt/vendor/github.com/govici/vici.(*Session).cmdTransportCommunicate(0x29022a0, 0x28c1c80, 0x0, 0x5cca70, 0x2897e90)
 /home/autobuild/project/cpe/linksdwan/workspace/src/owrt/vendor/github.com/govici/vici/requests.go:132 +0x48
owrt/vendor/github.com/govici/vici.(*Session).streamEventRegisterUnregister(0x29022a0, 0x653bfc, 0xb, 0x2a02f00, 0x1, 0x2bbecb8)
 /home/autobuild/project/cpe/linksdwan/workspace/src/owrt/vendor/github.com/govici/vici/requests.go:107 +0x6c
owrt/vendor/github.com/govici/vici.(*Session).handleStreamedRequest(0x29022a0, 0x651515, 0x8, 0x653bfc, 0xb, 0x2906530, 0x0, 0x7468d0, 0x2a02fa8)
 /home/autobuild/project/cpe/linksdwan/workspace/src/owrt/vendor/github.com/govici/vici/requests.go:80 +0x3f4
owrt/vendor/github.com/govici/vici.(*Session).sendStreamedRequest(0x29022a0, 0x651515, 0x8, 0x653bfc, 0xb, 0x2906530, 0x0, 0x0, 0x0)
 /home/autobuild/project/cpe/linksdwan/workspace/src/owrt/vendor/github.c


Usually,  when this happens, there is an error log "vici header read error: Connection reset by peer".

**Comment by enr0n** [comment] 2020-09-22 12:42
I still don't understand the issue exactly. Could you please do the following:

1. If possible, upgrade the package to the latest version (v0.5.0 as of now).
2. Post a code snippet of what you are *trying to do*.
3. Explain what you *expected* to happen
4. Explain what *is happening*

I understand that your modified code is printing that function stack, but I don't understand why you're modifying the code begin with.

**Comment by weixiaolan2019** [comment] 2020-09-23 02:55
I have upgraded the version to v0.5.0 now.

_ms, err := s.StreamedCommandRequest("initiate", "control-log", m)_

When I call function StreamedCommandRequest to do "initiate", or load other config, sometime the function may allocate a very big memory(about 110M, sometimes it may be more), I debug the function StreamedCommandRequest, and find the function will call "func (t *transport) recv() (*packet, error) ", and  in the recv function, "pl := binary.BigEndian.Uint32(buf)", I find the pl is a very big number(the pl is 118186863),  I think if the number is so big, the message is abnormal, so I suggest to check the validity of buf length "pl".

**Comment by enr0n** [comment] 2020-09-23 20:13
Okay, I'm understanding more now. Thanks.

To clarify, `StreamedCommandRequest` does not return an error in this case right? And are the messages in the `MessageStream` noticeably corrupt in anyway?

Are there any indicators of the issue besides the `vici header read error: Connection reset by peer` log message, and `pl` being very large?

I will try to reproduce this soon.

**Comment by weixiaolan2019** [comment] 2020-09-24 06:18
When pl is very big, StreamedCommandRequest does not return an error, no corrupt either.

Yesterday I found another problem, maybe it has relation to the issue, this is my code.

func CheckStatus() int {
	sess, err := vici.NewSession()
	if err != nil {
		return 0
	}
	ikeUpdown := "ike-updown"
	childUpdown := "child-updown"
	if err := sess.Subscribe(ikeUpdown, childUpdown); err != nil {
		sess.Close()
		return 0
	}
	for {
		_, err = sess.NextEvent(context.Background())
		if err != nil {
			**sess.Close()--------->It's hung here.**
			return 0
		} else {
			//do something
		}
	}
}

I find sometimes the code still is hung in sess.Close() (I have upgraded to v0.5.0), I debug the code, and find it's hung in function "func (el *eventListener) unregisterEvents(events []string, all bool) error", the function cannot get the lock "	el.emux.Lock()". To get more info, I debug the code in function  "func (el *eventListener) listen()", and find the lock is held here:
func (el *eventListener) listen() {
	.............................................
	for {
		select {
		...........................................................................................................
			// point in sending errors on the event channel. The error
			// must be for a event registration.
			el.emux.Lock()
                        cnt := len(el.events)
                        if len(el.events) > 0 {
				**el.ec <- Event{err: err} ----------->the code is hung here**
			}
			el.emux.Unlock()
			if cnt > 0 {
				fmt.Fprintf(os.Stderr, "emux.Unlock \n")
			}
                ...........................................................................................................

		}
		}
	}
}


What makes me surprise is that before the code is hung,  there is a very big packet received.

**Comment by bhatnitish** [comment] 2021-05-20 18:30
Any updates on this issue? I see the same issue in my setup too - I am running strongswan 5.9.0 on some arm nodes and use govici to talk to Charon and setup tunnels. I subscribe to the child-rekey and updown events. My test involves constant tunnel setup and teardown every minute and somewhere in this loop, govici tries to allocate a buf of 700MB and my process runs out of memory. Tracked it down to the same line as reported in this bug - for now I have added checks to limit pl to 500KB, any insights as to how to debug this more or why this happens will be appreciated.

**Comment by enr0n** [comment] 2021-05-20 18:50
@bhatnitish thanks for the additional information.

I believe the solution to this is to just read the packet in chunks if the packet length is larger than some limit. That should keep the buffer allocation reasonable. I can post a patch within the next week or so.

I am curious, however, what exactly is causing a packet of *700MB* to be generated from charon.

**Comment by enr0n** [comment] 2021-05-20 19:45
I may have spoke too soon; parsing all of that data into a single `packet` struct will still cause issues allocation issues.

@bhatnitish are you able to verify that charon is actually sending you a packet of 700MB? When you limit pl to 500KB, I assume that means you get incomplete messages, correct?

IIRC, charon is supposed to limit packet lengths to VICI_MESSAGE_SIZE_MAX (set at compile time, defaults to 512 * 1024). However, looking at [this function](https://github.com/strongswan/strongswan/blob/master/src/libcharon/plugins/vici/vici_socket.c#L312), it does not appear that the length is checked on write. It is checked in `do_read`, however.

**Comment by bhatnitish** [comment] 2021-05-21 02:21
I have added some logs when I see messages with abnormal header lengths, I also log the first 500KB of data. This issue is hard to reproduce, I usually see it after 7-8 hours of continuous events activity. Also, I don't receive some events when rekey happens or a child goes down due to DPD. I'm not sure if this is related to this issue - some sort of malformed packets leading to events being dropped. I'll update the thread if I see the malformed header. Maybe I could log these packets in do_write whenever the lengths go more than the 500KB limit? Any ideas how I could debug this further?

**Comment by enr0n** [comment] 2021-05-21 13:40
> I have added some logs when I see messages with abnormal header lengths, I also log the first 500KB of data. This issue is hard to reproduce, I usually see it after 7-8 hours of continuous events activity. 

Understood, please post any relevant logs when the issue does pop up again.

> Also, I don't receive some events when rekey happens or a child goes down due to DPD. I'm not sure if this is related to this issue - some sort of malformed packets leading to events being dropped. 

If you are able to confirm that charon is generating these events, and govici is not receiving them for some reason, feel free to open another issue. If charon is not generating the events, that would be outside the scope of this repository.

> I'll update the thread if I see the malformed header. Maybe I could log these packets in do_write whenever the lengths go more than the 500KB limit? Any ideas how I could debug this further?

Thanks. If you are able to re-compile the daemon for your environment, I think the best thing to do is add logging at the places events/messages are sent from the daemon. We need to check if the messages received by govici are consistent with what the daemon is actually generating. So, yes, logging large message lengths in do_write is a good idea.

If things are consistent between govici and the daemon, we may need to patch charon itself. But, if things are not consistent, we need to look at govici's transport and packet parsing code.

**Comment by bhatnitish** [comment] 2021-06-04 06:15
I added some logs to govici to nail this issue and this is what I see - 
2021-06-03 23:39:43 --> Header length: 823 buf: 070c6368696c642d7570646f776e0110506172656e742d32332e302e342e31300308756e697175656964000437393433030776657273696f6e00013203057374617465000844454c4554494e47030a6c6f63616c2d686f7374000932302e302e312e3131030a6c6f63616c2d706f7274000335303003086c6f63616c2d69640008434e3d6361707269030b72656d6f74652d686f7374000932332e302e342e3130030b72656d6f74652d706f72740003353030030972656d6f74652d6964000f434e3d373961343461663861373930030d696e69746961746f722d737069001063386231376662636331636263666663030d726573706f6e6465722d7370690010616662313562663334396562613931360308656e63722d616c6700074145535f434243030c656e63722d6b657973697a6500033235360309696e7465672d616c670011484d41435f534841325f3338345f31393203077072662d616c6700115052465f484d41435f534841325f333834030864682d67726f757000074543505f333834040d7461736b732d7061737369766505000a494b455f44454c4554450601096368696c642d73617301144368696c642d32332e302e342e31302d3138393503046e616d65000f4368696c642d32332e302e342e31300308756e6971756569640004313839350305726571696400023439030573746174650009494e5354414c4c454403046d6f646500095452414e53504f5254030870726f746f636f6c000345535003067370692d696e0008633331333662633603077370692d6f7574000863383232323332630308656e63722d616c6700074145535f434243030c656e63722d6b657973697a6500033235360309696e7465672d616c670011484d41435f534841325f3338345f313932030862797465732d696e000130030a7061636b6574732d696e000130030962797465732d6f7574000130030b7061636b6574732d6f7574000130030a72656b65792d74696d650005323730343403096c6966652d74696d6500053331363738030c696e7374616c6c2d74696d6500013204086c6f63616c2d747305000c32302e302e312e31312f333206040972656d6f74652d747305000c32332e302e342e31302f333206020202

2021-06-03 23:39:44 --> Header length: 902 buf: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

2021-06-03 23:39:44 --> Header - [7 12 99 104] data - 696c642d7570646f776e030275700003796573010f506172656e742d32332e302e342e330308756e697175656964000437393434030776657273696f6e00013203057374617465000b45535441424c4953484544030a6c6f63616c2d686f7374000932302e302e312e3131030a6c6f63616c2d706f7274000335303003086c6f63616c2d69640008434e3d6361707269030b72656d6f74652d686f7374000832332e302e342e33030b72656d6f74652d706f72740003353030030972656d6f74652d6964000f434e3d353463313633393831313...

So looks like, the header was read fine, and no data was read (all 0s) - I'll add a print to see if any error was returned here. Then the next header read basically read the data that was supposed to be read in the previous iteration - [7 12 99 104] basically points to a child-updown event.

**Comment by bhatnitish** [comment] 2021-06-04 06:30
Could this mean there was a delay between when the header and data was written to the stream by charon?

**Comment by enr0n** [comment] 2021-06-04 10:23
@bhatnitish Thanks for the update. Can you please post the diff showing your added log statements so that I can better understand the output?

**Comment by enr0n** [comment] 2021-06-10 22:29
@bhatnitish I came to the same conclusion about how the packet sizes were getting so large. It is clearly wrong for recv() to not make sure the correct number of bytes are being read. I think using io.ReadFull is a good fix for that piece.

As far as the read deadline, I am looking back through git history to figure out exactly why it is there. From an early look, I know it was originally added to keep the event listener loop moving. However, that code has been re-factored a couple times, and it may be safe for the event loop to block on that recv() call now.

**Comment by enr0n** [comment] 2021-06-29 15:27
@bhatnitish Have you had success with the extended deadline? If you are able, please try this branch: https://github.com/strongswan/govici/tree/fix-issue-34. If that works for you I will do a patch release with those commits.

**Comment by enr0n** [comment] 2021-08-25 00:46
The fix for this is included in the latest tag: https://github.com/strongswan/govici/releases/tag/v0.5.2.

**Closed by enr0n** 2021-08-25 00:46 UTC
Labels: bug
